version: '3'

services:
  database:
    image: mongo:5.0.16
    container_name: yolo_db_cont
    environment:
      MONGO_DB: yolomy
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - yolo_vol:/data/db
    networks:
      - yolo_network

  client:
    build: ./client
    image: kibetstephanie/yolo_client_image:v1.0.0
    container_name: yolo_client_cont
    environment:
      PORT: 3000
      PROXY_API: http://backend:5000/
    ports:
      - 3000:3000
    depends_on: 
      - backend
    networks:
      - yolo_network

  backend:
    image: kibetstephanie/yolo_backend_image:v1.0.0
    build: ./backend
    container_name: yolo_backend_cont
    environment:
      MONGODB_URI: mongodb://database:27017/yolomy
    ports:
      - 5000:5000
    depends_on: 
      - database
    networks:
      - yolo_network

volumes:
  yolo_vol:
    driver: local

networks:
  yolo_network:
    driver: bridge