---
- name: Yolo Application Playbook
  hosts: all
  become: yes

  vars_files:
    - name_vars.yml

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

  tasks:
    - name: Git Installation
      include_role:
        name: git
      
    - name: Installing Docker and Docker-compose
      include_role:
        name: docker

    - name: Run docker compose
      include_role:
        name: docker-compose

