apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: yolo-client-cont
          image: kibetstephanie/yolo_client_image:v1.0.0
          #imagePullPolicy: Never
          env:
            - name: PORT
              value: "3000"
            - name: PROXY_API
              value: "http://yolo-backend:5000/"
          ports:
            - containerPort: 3000