apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yolo-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-app-db
  serviceName: yolo-app-db
  template:
    metadata:
      labels:
        app: yolo-app-db
    spec:
      containers:
        - name: yolo-app-db
          image: mongo:5.0.16
          env:
            - name: MONGO_DB
              value: yolomy
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: yolo-app-data
              mountPath: /etc/data/backend
  volumeClaimTemplates:
    - metadata:
        name: yolo-dapp-ata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi